/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfirmDialog: typeof import('./components/common/ConfirmDialog.vue')['default']
    DatePicker: typeof import('./components/common/DatePicker.vue')['default']
    DialogAddMenu: typeof import('./components/UI/AppManagement/Menu/DialogAddMenu.vue')['default']
    DialogCreateUser: typeof import('./components/UI/Setting/Member/DialogCreateUser.vue')['default']
    DialogFormHeader: typeof import('./components/UI/AppManagement/Menu/DialogFormHeader.vue')['default']
    DialogFormMember: typeof import('./components/UI/Setting/Member/DialogFormMember.vue')['default']
    DialogFormMenu: typeof import('./components/UI/AppManagement/Menu/DialogFormMenu.vue')['default']
    DialogFormRole: typeof import('./components/UI/AppManagement/Role/DialogFormRole.vue')['default']
    DialogFormRoleMenu: typeof import('./components/UI/AppManagement/RoleMenu/DialogFormRoleMenu.vue')['default']
    DialogFormUser: typeof import('./components/UI/AppManagement/User/DialogFormUser.vue')['default']
    DialogImportMember: typeof import('./components/UI/Setting/Member/DialogImportMember.vue')['default']
    DialogRoleSelection: typeof import('./components/UI/Setting/Member/DialogRoleSelection.vue')['default']
    DialogStructureMenu: typeof import('./components/UI/AppManagement/Menu/DialogStructureMenu.vue')['default']
    DuesList: typeof import('./components/UI/Finance/Dues/DuesList.vue')['default']
    FormDataMenu: typeof import('./components/UI/AppManagement/Menu/FormDataMenu.vue')['default']
    HistoryList: typeof import('./components/UI/Finance/CashBalance/HistoryList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TinyMCE: typeof import('./components/common/TinyMCE.vue')['default']
    TipTap: typeof import('./components/common/TipTap.vue')['default']
    TipTapSimple: typeof import('./components/common/TipTapSimple.vue')['default']
    UploadProofDialog: typeof import('./components/UI/Finance/Dues/UploadProofDialog.vue')['default']
  }
}
