/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/AppManagement/Menu/Index': RouteRecordInfo<'/AppManagement/Menu/Index', '/AppManagement/Menu/Index', Record<never, never>, Record<never, never>>,
    '/AppManagement/Role/Index': RouteRecordInfo<'/AppManagement/Role/Index', '/AppManagement/Role/Index', Record<never, never>, Record<never, never>>,
    '/AppManagement/RoleMenu/Index': RouteRecordInfo<'/AppManagement/RoleMenu/Index', '/AppManagement/RoleMenu/Index', Record<never, never>, Record<never, never>>,
    '/AppManagement/User/Index': RouteRecordInfo<'/AppManagement/User/Index', '/AppManagement/User/Index', Record<never, never>, Record<never, never>>,
    '/Finance/CashBalance/Index': RouteRecordInfo<'/Finance/CashBalance/Index', '/Finance/CashBalance/Index', Record<never, never>, Record<never, never>>,
    '/Finance/Dues/Index': RouteRecordInfo<'/Finance/Dues/Index', '/Finance/Dues/Index', Record<never, never>, Record<never, never>>,
    '/Home': RouteRecordInfo<'/Home', '/Home', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/NotFound': RouteRecordInfo<'/NotFound', '/NotFound', Record<never, never>, Record<never, never>>,
    '/Setting/AboutTimelines/Index': RouteRecordInfo<'/Setting/AboutTimelines/Index', '/Setting/AboutTimelines/Index', Record<never, never>, Record<never, never>>,
    '/Setting/Activities/Index': RouteRecordInfo<'/Setting/Activities/Index', '/Setting/Activities/Index', Record<never, never>, Record<never, never>>,
    '/Setting/Core/Index': RouteRecordInfo<'/Setting/Core/Index', '/Setting/Core/Index', Record<never, never>, Record<never, never>>,
    '/Setting/Landing/Index': RouteRecordInfo<'/Setting/Landing/Index', '/Setting/Landing/Index', Record<never, never>, Record<never, never>>,
    '/Setting/Member/Index': RouteRecordInfo<'/Setting/Member/Index', '/Setting/Member/Index', Record<never, never>, Record<never, never>>,
  }
}
